apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: lgwm-image
        image: asia-south1-docker.pkg.dev/s-0-009988/docker-images/canary:v1
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: lgwm-image
        image: asia-south1-docker.pkg.dev/s-0-009988/docker-images/canary:v2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  type: LoadBalancer
  selector:
    app: canary
  ports:
  - port: 8080
    targetPort: 80
