pipeline {
    agent any

    environment {
        PROJECT_ID = "s-0-009988"
        #REGION = "asia-south1"
        REPO = "asia-south1-docker.pkg.dev/s-0-009988/docker-images"
        IMAGE = "myapp"
        IMAGE_TAG = "v${BUILD_NUMBER}"
        CLUSTER_ZONE = "gitlab-gke"
        ZONE = "asia-south1-c"
        COLOR = "blue"     // Jenkins decides dynamically
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Vire-cloud/helm.git'
            }
        }

        stage('Authenticate to GCP') {
            steps {
                withCredentials([file(credentialsId: 'service-account', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh '''
                    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                    gcloud config set project $PROJECT_ID
                    gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID
                    '''
                }
            }
        }        

        stage('Docker Build & Push') {
            steps {
                sh """
                gcloud auth configure-docker asia-south1-docker.pkg.dev -q
                docker build -t ${Repository}/$IMAGE_NAME:$IMAGE_TAG .
                docker push ${Repository}/$IMAGE_NAME:$IMAGE_TAG
                """
            }
        }

        stage('Deploy New Color') {
            steps {
                sh """
                helm upgrade --install myapp-${COLOR} ./helm/myapp \
                  --values helm/myapp/values-${COLOR}.yaml \
                  --set image.repository=${REPO}/$IMAGE_NAME \
                  --set image.tag=$IMAGE_TAG \
                  --wait --timeout 1m
                """
            }
        }

\\        stage('Switch Traffic to New Color') {
\\            steps {
\\                sh """
\\                helm upgrade myapp ./helm/myapp \
\\                  --set color=${NEW_COLOR}
\\               """
\\            }
\\       }
\\    }

    post {
        failure {
            echo "Deployment failed — Traffic NOT switched."
        }
    }
}

