pipeline {
    agent any

    environment {
        PROJECT_ID = "s-0-009988"
        IMAGE_NAME = "online_shop"
        CLUSTER_NAME= "gitlab-gke"
        CLUSTER_ZONE= "asia-south1-c"
        IMAGE_TAG = "v${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Vire-cloud/helm.git'
            }
        }

        stage('Authenticate to GCP') {
            steps {
                withCredentials([file(credentialsId: 'service-account', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh '''
                    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                    gcloud config set project $PROJECT_ID
                    gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID
                    '''
                }
            }
        }
        stage('build and push') {
            steps {
                sh '''
                gcloud auth configure-docker asia-south1-docker.pkg.dev -q
                docker build -t ${Repository}/$IMAGE_NAME:$IMAGE_TAG .
                docker push ${Repository}/$IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }    
        stage('deploy with kubectl') {
           steps {
               sh '''
               mkdir -p ~/.kube
               echo "${KUBE_CONFIG}" > ~/.kube/config
               kubectl apply -f Blue-green-deployment/blue-green-ns.yml
               kubectl apply -f Blue-green-deployment/online-shop-without-footer-blue-deployment.yaml
               #kubectl apply -f Blue-green-deployment/online-shop-green-deployment.yaml
               --wait --timeout 1m
               '''
           }
        } 
        stage('Verify Deployment') {
            steps {
                sh '''
                echo "Verifying resources..."
                kubectl get pods -n blue-green-ns
                kubectl get svc -n blue-green-ns
                '''
            }
        }        
    }
}    

