pipeline {
    agent any

    environment {
        PROJECT_ID = "YOUR_GCP_PROJECT_ID"
        IMAGE_NAME = "online_shop"
        GCR_IMAGE = "gcr.io/${PROJECT_ID}/${IMAGE_NAME}"
        KUBE_CONFIG = credentials('K8S_CONFIG')
        GOOGLE_CREDENTIALS = credentials('GCR_JSON')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Vire-cloud/helm.git'
            }
        }

        stage('Authenticate to GCP') {
            steps {
                withCredentials([file(credentialsId: 'service-account', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    sh '''
                    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
                    gcloud config set project $PROJECT_ID
                    gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID
                    '''
                }
            }
        }

