apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      version: stable
  template:
    metadata:
      labels:
        app: app
        version: stable
    spec:
      containers:
      - name: app-container
        image: asia-south1-docker.pkg.dev/s-0-009988/docker-images/stable:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
